
package org.securecode.smartcard.gui;

import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;
import org.securecode.smartcard.tools.SHA;

/**
 * Clase grafica para obtener los datos del usuario
 *
 * @author Ing. Felipe Giraldo
 * @since Creado el 20 de junio de 2014
 * @version 1.0
 */
public class DatosUsuario extends javax.swing.JFrame {

    /**
     * Logger de clase
     */
    private static final Logger logger = Logger.getLogger(DatosUsuario.class);
    
    /**
     * Creates new form DatosUsuario
     */
    public DatosUsuario() {
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormulario = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        tFldLogin = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        lblPin = new javax.swing.JLabel();
        pwdPin = new javax.swing.JPasswordField();
        btnGenerar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos del Usuario");

        lblFormulario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFormulario.setText("Datos del Usuario");
        lblFormulario.setFocusable(false);

        lblInformacion.setText("Ingrese los datos del usuario a continuación:");
        lblInformacion.setFocusable(false);

        lblLogin.setText("Login");
        lblLogin.setFocusable(false);

        tFldLogin.setNextFocusableComponent(pwdPassword);

        lblPassword.setText("Pasword");
        lblPassword.setFocusable(false);

        pwdPassword.setNextFocusableComponent(pwdPin);

        lblPin.setText("Pin");
        lblPin.setFocusable(false);

        pwdPin.setNextFocusableComponent(btnGenerar);

        btnGenerar.setText("Generar");
        btnGenerar.setNextFocusableComponent(btnLimpiar);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setNextFocusableComponent(btnVolver);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.setNextFocusableComponent(tFldLogin);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormulario)
                    .addComponent(lblInformacion)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin)
                            .addComponent(lblPassword)
                            .addComponent(lblPin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdPin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolver)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblLogin, lblPassword, lblPin});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGenerar, btnLimpiar, btnVolver});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pwdPassword, pwdPin, tFldLogin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormulario)
                .addGap(18, 18, 18)
                .addComponent(lblInformacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(tFldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(pwdPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVolver))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        
        String login = tFldLogin.getText();
        String password = pwdPassword.getText();
        String pin = pwdPin.getText();
        
        if (StringUtils.isBlank(login) || StringUtils.isBlank(password) || StringUtils.isBlank(pin) || !StringUtils.isNumeric(pin)) {
            JOptionPane.showMessageDialog(null, "Error en los parámetros de entrada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Valida la longitud del login, en BD es 30
        if (login.length() > 12) {
            JOptionPane.showMessageDialog(null, "Error en los parámetros de entrada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Valida la longitud del password, en BD es 32
        if (password.length() > 12) {
            JOptionPane.showMessageDialog(null, "Error en los parámetros de entrada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (pin.length() != 4) {
            JOptionPane.showMessageDialog(null, "Error en los parámetros de entrada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String build = buildKey(login, password, pin);
        build = build.substring(0, 16);
        new GenerarBatch(build).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        
        tFldLogin.setText("");
        pwdPassword.setText("");
        pwdPin.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblFormulario;
    private javax.swing.JLabel lblInformacion;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPin;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdPin;
    private javax.swing.JTextField tFldLogin;
    // End of variables declaration//GEN-END:variables

    private String buildKey(String idUsuario, String passUsuario, String pinUsuario) {
        
        passUsuario = getMd5(passUsuario);
            
        StringBuilder build = new StringBuilder();
        build.append(idUsuario);
        build.append("|");
        build.append(passUsuario);
        build.append("|");
        build.append(pinUsuario);
        
        String retorno = SHA.getSHA256(build.toString());
        if (StringUtils.isNotBlank(retorno))
            return retorno;
        else
            return null;
    }
    
    public String getMd5(String message) {
        
        String digest = null;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] hash = md.digest(message.getBytes("UTF-8"));
            StringBuilder sb = new StringBuilder(2*hash.length);
            for (byte b : hash) {
                sb.append(String.format("%02x", b&0xff));
            }
            digest = sb.toString();
        }
        catch (UnsupportedEncodingException | NoSuchAlgorithmException ex) {
            logger.error("Error: " + ex.getMessage());
        }
        return digest;
    }
    
}
